import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import '../globals.css';
import NavBar from '../../components/Sidebar/Sideruser';
import Footer from '../../components/Footer/Footer';

export const metadata = {
  title: 'Zelos | Senai',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
